apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: snake-game
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/IZK8SCluster/snake
  ref:
    branch: main

---

apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: snake-game
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./apps
  prune: true
  sourceRef:
    kind: GitRepository
    name: snake-game
  targetNamespace: snake-game
