apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: snake-game
  name: snake-game
spec:
  replicas: 2
  selector:
    matchLabels:
      app: snake-game
  strategy: {}
  template:
    metadata:
      labels:
        app: snake-game
    spec:
      containers:
      - image: ptomar25/snakegame
        name: snake-game
        ports:
        - containerPort: 3000


---
apiVersion: v1
kind: Service
metadata:
  name: snake-game-service
  labels:
    app: snake-game-service
spec:
  type: NodePort
  ports:
  - name: snake-game
    port: 3000
  selector:
    app: snake-game

